/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_iwebrtc_audioprocess_sdk_AudioProcess */

#ifndef _Included_net_iwebrtc_audioprocess_sdk_AudioProcess
#define _Included_net_iwebrtc_audioprocess_sdk_AudioProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_iwebrtc_audioprocess_sdk_AudioProcess
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_net_iwebrtc_audioprocess_sdk_AudioProcess_create
  (JNIEnv *, jobject);

/*
 * Class:     net_iwebrtc_audioprocess_sdk_AudioProcess
 * Method:    set_config
 * Signature: (II)J
 */
JNIEXPORT jint JNICALL Java_net_iwebrtc_audioprocess_sdk_AudioProcess_set_1config
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_iwebrtc_audioprocess_sdk_AudioProcess
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_net_iwebrtc_audioprocess_sdk_AudioProcess_init
  (JNIEnv *, jobject);

/*
 * Class:     net_iwebrtc_audioprocess_sdk_AudioProcess
 * Method:    processStream10msData
 * Signature: ([BI[BI[B)Z
 */
JNIEXPORT jboolean JNICALL Java_net_iwebrtc_audioprocess_sdk_AudioProcess_processStream10msData
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint, jbyteArray);

/*
 * Class:     net_iwebrtc_audioprocess_sdk_AudioProcess
 * Method:    destroy
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_iwebrtc_audioprocess_sdk_AudioProcess_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
